### ISSUE TITLE
Podatki od Promet.si

### ISSUE THREAD

**Issue by Mikhail111** [zejn/prometapi#6]
Thank you

**Comment by zejn** [comment]
Be aware that this is an unofficial API. For the most part it only transforms XML provided by promet.si to JSON, the only thing added are Google maps compatible WGS84 coordinates in SRID 4326.

Also, I don't think promet.si uses the same data as is on Google maps.

The way I see it now the traffic jam data on promet.si is layered on top of tiles and not a separate layer. While I think it's possible to scrape this, a better option might be to first try to contact the promet.si administrator at info@promet.si to see if it is possible to obtain the data in machine readable format.

Lep pozdrav,
Gašper Ž.
